apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-central
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: default

  source:
    repoURL: https://github.com/rakesh611/RHCAS_Install_Through_ArgoCD.git
    targetRevision: main
    path: rhacs/central

  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
