apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
spec:
  egress:
    connectivityPolicy: Online

  monitoring:
    openshift:
      enabled: true

  network:
    policies: Enabled

  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true

    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
        storageClassName: lvms-vg1
        size: 50Gi

    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
          storageClassName: lvms-vg1
          size: 20Gi

  scannerV4:
    scannerComponent: Enabled

    indexer:
      scaling:
        autoScaling: Enabled
        minReplicas: 1
        maxReplicas: 2

    matcher:
      scaling:
        autoScaling: Enabled
        minReplicas: 1
        maxReplicas: 2

    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
          storageClassName: lvms-vg1
          size: 20Gi
